### ISSUE TITLE
Compatibility issue with Pytorch

### ISSUE THREAD

**Issue by SingletC** [tblite/tblite#110]
I found this strange behavior of tblite in Python if PyTorch was imported.
```
import torch
from tblite.ase import TBLite
from ase.atoms import Atoms
import numpy as np
atoms = Atoms(
    symbols="C4O8",
    positions=np.array(
        [
            [0.9441259872, 0.9437851680, 0.9543505632],
            [3.7179966528, 0.9556570368, 3.7316862240],
            [3.7159517376, 3.7149292800, 0.9692330016],
            [0.9529872864, 3.7220864832, 3.7296981120],
            [1.6213905408, 1.6190616096, 1.6313879040],
            [0.2656685664, 0.2694175776, 0.2776540416],
            [4.3914553920, 1.6346256864, 3.0545920000],
            [3.0440834880, 0.2764611744, 4.4080419264],
            [4.3910577696, 3.0416409504, 0.2881058304],
            [3.0399936576, 4.3879335936, 1.6497353376],
            [0.2741322432, 4.4003734944, 3.0573754368],
            [1.6312174944, 3.0434586528, 4.4023048032],
        ]
    ),
    cell=np.array([5.68032, 5.68032, 5.68032]),
    pbc=np.array([True, True, True]),
)
atoms.calc = TBLite(method="GFN1-xTB")
atoms.get_potential_energy()  # result in eV
```
I got below output and it will never converge.
```
------------------------------------------------------------
  cycle        total energy    energy error   density error
------------------------------------------------------------
      1     -220145.1130691  -2.2014835E+05   2.2662454E+01
      2     -40994493.39613  -4.0774348E+07   2.5360774E+01
      3     -41798970.97528  -8.0447758E+05   2.1118388E+01
      4     -41231779.00001   5.6719198E+05   4.2775653E+00
      5     -41176517.54710   5.5261453E+04   2.1617182E+00
      6     -40929947.88949   2.4656966E+05   2.0241658E+00
      7     -40916228.61312   1.3719276E+04   1.5423235E+00
      8     -41175248.31226  -2.5901970E+05   1.8033720E+00
      9     -41075903.51087   9.9344801E+04   1.8529595E+00
     10     -41214458.36624  -1.3855486E+05   1.6252884E+00
     11     -41186215.84712   2.8242519E+04   1.2174420E+00
     12     -41076999.56984   1.0921628E+05   1.5036796E+00
     13     -40914319.21158   1.6268036E+05   1.0555325E+00
     14     -41803486.23037  -8.8916702E+05   1.1167128E+00
     15     -41425955.91671   3.7753031E+05   7.6022145E-01
     16     -41304348.50592   1.2160741E+05   1.2073868E+00
     17     -41771834.81548  -4.6748631E+05   9.9171739E-01
     18     -41090587.65317   6.8124716E+05   9.7361783E-01
     19     -41803487.78510  -7.1290013E+05   9.0392384E-01
     20     -40980774.06874   8.2271372E+05   8.5913280E-01
     21     -41803489.59767  -8.2271553E+05   5.3896947E-01
     22     -39982953.84887   1.8205357E+06   9.5528544E-01
     23     -41305192.47564  -1.3222386E+06   6.9177270E-01
     24     -41268485.27003   3.6707206E+04   5.5739283E-01
     25     -41478496.45580  -2.1001119E+05   6.3010293E-01
     26     -40702421.14412   7.7607531E+05   7.1690218E-01
     27     -39651186.85413   1.0512343E+06   1.2553164E+00
     28     -40949242.17474  -1.2980553E+06   6.1052683E-01
     29     -41001412.34763  -5.2170173E+04   5.5212886E-01
     30     -41073869.01141  -7.2456664E+04   7.7515769E-01
     31     -41737795.31617  -6.6392630E+05   1.9723712E-01
     32     -41801158.60198  -6.3363286E+04   2.2661286E-01
     33     -41661436.55195   1.3972205E+05   4.3782619E-01
     34     -41674543.69094  -1.3107139E+04   3.5255131E-01
     35     -41173591.11277   5.0095258E+05   4.4963589E-01
     36     -41788959.06234  -6.1536795E+05   2.8875074E-01
     37     -41797570.46348  -8.6114011E+03   2.4509764E-01
     38     -41668462.37089   1.2910809E+05   4.0788906E-01
     39     -41803490.37610  -1.3502801E+05   2.4518633E-01
     40     -41803490.44519  -6.9086663E-02   1.9533992E-01
     41     -41703372.46342   1.0011798E+05   3.2203525E-01
...
```
change the order of import solve the issue:
```
from tblite.ase import TBLite
import torch
from ase.atoms import Atoms
import numpy as np
atoms = Atoms(
    symbols="C4O8",
    positions=np.array(
        [
            [0.9441259872, 0.9437851680, 0.9543505632],
            [3.7179966528, 0.9556570368, 3.7316862240],
            [3.7159517376, 3.7149292800, 0.9692330016],
            [0.9529872864, 3.7220864832, 3.7296981120],
            [1.6213905408, 1.6190616096, 1.6313879040],
            [0.2656685664, 0.2694175776, 0.2776540416],
            [4.3914553920, 1.6346256864, 3.0545920000],
            [3.0440834880, 0.2764611744, 4.4080419264],
            [4.3910577696, 3.0416409504, 0.2881058304],
            [3.0399936576, 4.3879335936, 1.6497353376],
            [0.2741322432, 4.4003734944, 3.0573754368],
            [1.6312174944, 3.0434586528, 4.4023048032],
        ]
    ),
    cell=np.array([5.68032, 5.68032, 5.68032]),
    pbc=np.array([True, True, True]),
)
atoms.calc = TBLite(method="GFN1-xTB")
atoms.get_potential_energy()  # result in eV
------------------------------------------------------------
  cycle        total energy    energy error   density error
------------------------------------------------------------
      1     -44.18466375638  -4.4584172E+01   9.5746031E-01
      2     -46.17349195524  -1.9888282E+00   3.7709276E-01
      3     -46.19352636164  -2.0034406E-02   2.1480769E-01
      4     -46.18634789943   7.1784622E-03   6.1688940E-02
      5     -46.19681129475  -1.0463395E-02   3.3123492E-03
      6     -46.19683700903  -2.5714277E-05   1.4081482E-03
      7     -46.19684187755  -4.8685184E-06   4.2127827E-04
      8     -46.19684228849  -4.1094205E-07   1.2814394E-04
      9     -46.19684233075  -4.2263878E-08   5.6634669E-06
------------------------------------------------------------
 total:                                   0.550 sec
Out[6]: -1257.0801097690023
```
my environment is python3.9 
conda-forge installed tblite  0.3.0
I tested both Torch version 1.8.1+cu102 and 2.0.1+cpu

**Comment by Andrew-S-Rosen** [comment]
Looks to be virtually the same issue as #116. I only just saw this. I can reproduce this behavior on Python 3.11 and torch 2.0.1. I used `pip install tblite[ase]`.

**Comment by awvwgk** [comment]
I would like to help here, but I need some insight on the provenance of the packages in the environment (like `conda list`). Are pytorch and tblite installed from the same channel (conda-forge) is one installed from PyPI and vendoring libraries, like gomp in pytorch?

**Comment by Andrew-S-Rosen** [comment]
In my case, both are installed via pip. I will provide more details in the AM here though!

**Comment by awvwgk** [comment]
The tblite version from PyPI is vendoring the conda-forge shared libraries, not sure where the shared libraries in the torch wheels are coming from, but I can imagine that there might be a conflict. One option would be to figure out how torch wheels are built and use the same environment to build the tblite wheels.

**Comment by Andrew-S-Rosen** [comment]
Yeah I don't know too much about how `torch` is built myself. We just happened to stumble upon this in the `Pymatgen` repo because both dependencies happened to be installed in the unit tests. A clean conda env with `pip install tblite[ase]` and `pip install torch` on Ubuntu and Python 3.11 reproduces the behavior. I don't have much more info to provide I suppose, but if there's any other testing I can do that might help, feel free to let me know. I do think there is some incompatibility due to the shared libraries like you said.

**Comment by Andrew-S-Rosen** [comment]
Tagging @samblau.

**Comment by ShangChien** [comment]
### My code run into the same problem：
- `import torch` after `import TBLite` is OK

```py
from tblite.ase import TBLite
import torch
from ase.atoms import Atoms
import numpy as np
atoms = Atoms(
    symbols="C4O8",
    positions=np.array(
        [
            [0.9441259872, 0.9437851680, 0.9543505632],
            [3.7179966528, 0.9556570368, 3.7316862240],
            [3.7159517376, 3.7149292800, 0.9692330016],
            [0.9529872864, 3.7220864832, 3.7296981120],
            [1.6213905408, 1.6190616096, 1.6313879040],
            [0.2656685664, 0.2694175776, 0.2776540416],
            [4.3914553920, 1.6346256864, 3.0545920000],
            [3.0440834880, 0.2764611744, 4.4080419264],
            [4.3910577696, 3.0416409504, 0.2881058304],
            [3.0399936576, 4.3879335936, 1.6497353376],
            [0.2741322432, 4.4003734944, 3.0573754368],
            [1.6312174944, 3.0434586528, 4.4023048032],
        ]
    ),
    cell=np.array([5.68032, 5.68032, 5.68032]),
    pbc=np.array([True, True, True]),
)
atoms.calc = TBLite(method="GFN1-xTB")
atoms.get_potential_energy()
------------------------------------------------------------
  cycle        total energy    energy error   density error
------------------------------------------------------------
      1     -44.18466375638  -4.4584172E+01   9.5746031E-01
      2     -46.17349195524  -1.9888282E+00   3.7709276E-01
      3     -46.19352636164  -2.0034406E-02   2.1480769E-01
      4     -46.18634789943   7.1784622E-03   6.1688940E-02
      5     -46.19681129475  -1.0463395E-02   3.3123492E-03
      6     -46.19683700903  -2.5714277E-05   1.4081482E-03
      7     -46.19684187755  -4.8685185E-06   4.2127827E-04
      8     -46.19684228849  -4.1094203E-07   1.2814394E-04
      9     -46.19684233075  -4.2263885E-08   5.6634669E-06
------------------------------------------------------------


```

- `import torch` before `import TBLite`, get an error:

```py
import torch
from tblite.ase import TBLite
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sanyue/miniconda3/envs/unimol/lib/python3.10/site-packages/tblite/library.py", line 28, in <module>
    from ._libtblite import ffi, lib
ImportError: /home/sanyue/miniconda3/envs/unimol/lib/python3.10/site-packages/torch/lib/libgomp-a34b3233.so.1: version `GOMP_5.0' not found (required by /home/sanyue/miniconda3/envs/unimol/lib/python3.10/site-packages/tblite/../../../libtblite.so.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sanyue/webapp/backEnd/backend/backend.0.1/test_tmp/tblite_test.py", line 2, in <module>
    from tblite.ase import TBLite
  File "/home/sanyue/miniconda3/envs/unimol/lib/python3.10/site-packages/tblite/ase.py", line 32, in <module>
    from .interface import Calculator
  File "/home/sanyue/miniconda3/envs/unimol/lib/python3.10/site-packages/tblite/interface.py", line 26, in <module>
    from . import library
  File "/home/sanyue/miniconda3/envs/unimol/lib/python3.10/site-packages/tblite/library.py", line 30, in <module>
    raise ImportError("tblite C extension unimportable, cannot use C-API")
ImportError: tblite C extension unimportable, cannot use C-API

```
### env :
- tblite                    0.3.0                h03160e7_0    conda-forge
- tblite-python             0.3.0           py310h2372a71_2    conda-forge
- torch                     2.0.1                    pypi_0    pypi
- conda:
```sh
active environment : mol
    active env location : /home/sanyue/miniconda3/envs/mol
            shell level : 1
       user config file : /home/sanyue/.condarc
 populated config files : /home/sanyue/.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.8.15.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.31=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /home/sanyue/miniconda3  (writable)
      conda av data dir : /home/sanyue/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/sanyue/miniconda3/pkgs
                          /home/sanyue/.conda/pkgs
       envs directories : /home/sanyue/miniconda3/envs
                          /home/sanyue/.conda/envs
               platform : linux-64
             user-agent : conda/22.11.1 requests/2.28.1 CPython/3.8.15 Linux/5.15.0-88-generic ubuntu/20.04.2 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
👋 thank you!

**Comment by SingletC** [comment]
I confirmed the issue is from when libtorch_global_deps.so is imorted in torch as:
https://github.com/pytorch/pytorch/blob/8173d98c575034916f1513ba6d1afa7b19352fe5/torch/__init__.py#L237
from the torch's dev notes, it is likely an OpenMPI issue.
https://github.com/pytorch/pytorch/blob/8173d98c575034916f1513ba6d1afa7b19352fe5/caffe2/CMakeLists.txt#L1586

**Comment by corinwagen** [comment]
Any headway here? This is a pretty frustrating error.

**Comment by awvwgk** [comment]
The way forward seems to compile without OpenMP support for now, which does limit the capability of tblite to run in parallel.
